0:
  label : 'background'
  activated : True
  confidence_threshold : 0.1
1:
  label : 'person'
  activated : True
  confidence_threshold : 0.7
2:
  label : 'bicycle'
  activated : False
  confidence_threshold : 0.1
3:
  label : 'car'
  activated : False
  confidence_threshold : 0.1
4:
  label : 'motorcycle'
  activated : False
  confidence_threshold : 0.1
5:
  label : 'airplane'
  activated : False
  confidence_threshold : 0.1
6:
  label : 'bus'
  activated : False
  confidence_threshold : 0.1
7:
  label : 'train'
  activated : False
  confidence_threshold : 0.1
8:
  label : 'truck'
  activated : False
  confidence_threshold : 0.1
9:
  label : 'boat'
  activated : False
  confidence_threshold : 0.1
10:
  label : 'traffic_light'
  activated : False
  confidence_threshold : 0.1
11:
  label : 'fire_hydrant'
  activated : False
  confidence_threshold : 0.1
12:
  label : 'stop_sign'
  activated : False
  confidence_threshold : 0.1
13:
  label : 'parking_meter'
  activated : False
  confidence_threshold : 0.1
14:
  label : 'bench'
  activated : False
  confidence_threshold : 0.1
15:
  label : 'bird'
  activated : False
  confidence_threshold : 0.1
16:
  label : 'cat'
  activated : False
  confidence_threshold : 0.1
17:
  label : 'dog'
  activated : False
  confidence_threshold : 0.1
18:
  label : 'horse'
  activated : False
  confidence_threshold : 0.1
19:
  label : 'sheep'
  activated : False
  confidence_threshold : 0.1
20:
  label : 'cow'
  activated : False
  confidence_threshold : 0.1
21:
  label : 'elephant'
  activated : False
  confidence_threshold : 0.1
22:
  label : 'bear'
  activated : False
  confidence_threshold : 0.1
23:
  label : 'zebra'
  activated : False
  confidence_threshold : 0.1
24:
  label : 'giraffe'
  activated : False
  confidence_threshold : 0.1
25:
  label : 'backpack'
  activated : False
  confidence_threshold : 0.1
26:
  label : 'umbrella'
  activated : False
  confidence_threshold : 0.1
27:
  label : 'handbag'
  activated : False
  confidence_threshold : 0.1
28:
  label : 'tie'
  activated : False
  confidence_threshold : 0.1
29:
  label : 'suitcase'
  activated : False
  confidence_threshold : 0.1
30:
  label : 'frisbee'
  activated : False
  confidence_threshold : 0.1
31:
  label : 'skis'
  activated : False
  confidence_threshold : 0.1
32:
  label : 'snowboard'
  activated : False
  confidence_threshold : 0.1
33:
  label : 'sports_ball'
  activated : False
  confidence_threshold : 0.1
34:
  label : 'kite'
  activated : False
  confidence_threshold : 0.1
35:
  label : 'baseball_bat'
  activated : False
  confidence_threshold : 0.1
36:
  label : 'baseball_glove'
  activated : False
  confidence_threshold : 0.1
37:
  label : 'skateboard'
  activated : False
  confidence_threshold : 0.1
38:
  label : 'surfboard'
  activated : False
  confidence_threshold : 0.1
39:
  label : 'tennis_racket'
  activated : False
  confidence_threshold : 0.1
40:
  label : 'bottle'
  activated : False
  confidence_threshold : 0.1
41:
  label : 'wine_glass'
  activated : False
  confidence_threshold : 0.1
42:
  label : 'cup'
  activated : False
  confidence_threshold : 0.1
43:
  label : 'fork'
  activated : False
  confidence_threshold : 0.1
44:
  label : 'knife'
  activated : False
  confidence_threshold : 0.1
45:
  label : 'spoon'
  activated : False
  confidence_threshold : 0.1
46:
  label : 'bowl'
  activated : False
  confidence_threshold : 0.1
47:
  label : 'banana'
  activated : False
  confidence_threshold : 0.1
48:
  label : 'apple'
  activated : False
  confidence_threshold : 0.1
49:
  label : 'sandwich'
  activated : False
  confidence_threshold : 0.1
50:
  label : 'orange'
  activated : False
  confidence_threshold : 0.1
51:
  label : 'broccoli'
  activated : False
  confidence_threshold : 0.1
52:
  label : 'carrot'
  activated : False
  confidence_threshold : 0.1
53:
  label : 'hot_dog'
  activated : False
  confidence_threshold : 0.1
54:
  label : 'pizza'
  activated : False
  confidence_threshold : 0.1
55:
  label : 'donut'
  activated : False
  confidence_threshold : 0.1
56:
  label : 'cake'
  activated : False
  confidence_threshold : 0.1
57:
  label : 'chair'
  activated : False
  confidence_threshold : 0.1
58:
  label : 'couch'
  activated : False
  confidence_threshold : 0.1
59:
  label : 'potted_plant'
  activated : False
  confidence_threshold : 0.1
60:
  label : 'bed'
  activated : False
  confidence_threshold : 0.1
61:
  label : 'dining_table'
  activated : False
  confidence_threshold : 0.1
62:
  label : 'toilet'
  activated : False
  confidence_threshold : 0.1
63:
  label : 'tv'
  activated : False
  confidence_threshold : 0.1
64:
  label : 'laptop'
  activated : False
  confidence_threshold : 0.1
65:
  label : 'mouse'
  activated : False
  confidence_threshold : 0.1
66:
  label : 'remote'
  activated : False
  confidence_threshold : 0.1
67:
  label : 'keyboard'
  activated : False
  confidence_threshold : 0.1
68:
  label : 'cell_phone'
  activated : False
  confidence_threshold : 0.1
69:
  label : 'microwave'
  activated : False
  confidence_threshold : 0.1
70:
  label : 'oven'
  activated : False
  confidence_threshold : 0.1
71:
  label : 'toaster'
  activated : False
  confidence_threshold : 0.1
72:
  label : 'sink'
  activated : False
  confidence_threshold : 0.1
73:
  label : 'refrigerator'
  activated : False
  confidence_threshold : 0.1
74:
  label : 'book'
  activated : False
  confidence_threshold : 0.1
75:
  label : 'clock'
  activated : False
  confidence_threshold : 0.1
76:
  label : 'vase'
  activated : False
  confidence_threshold : 0.1
77:
  label : 'scissors'
  activated : False
  confidence_threshold : 0.1
78:
  label : 'teddy_bear'
  activated : False
  confidence_threshold : 0.1
79:
  label : 'hair_drier'
  activated : False
  confidence_threshold : 0.1
80:
  label : 'toothbrush'
  activated : False
  confidence_threshold : 0.1
